In [2]:
import numpy as np

In [18]:
array = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [5]:
flatten= array.flatten()

In [6]:
print(flatten)

[1 2 3 4 5 6 6 7 8]


In [20]:
reshape=array.reshape((3,3))
print(reshape)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [13]:
ravel=array.ravel()
print(ravel)

[1 2 3 4 5 6 6 7 8]


In [14]:
transpose=array.T
print(transpose)

[[1 4 6]
 [2 5 7]
 [3 6 8]]


In [21]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
arr1=np.random.randint(0,100,size=(3,4))
print(arr1)

[[54  4 42 53]
 [97 81 57 23]
 [25 41 22 52]]
